---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{r Class Objects, echo=FALSE}

library(DLMtool)
library(tools)
library(htmlTable)
library(pander)

db <- Rd_db("DLMtool")

## Make Cheat Sheets for Classes ----
Classes <- grep("-class", names(db))

# for (Class in Classes) {
Class <- 144
temp <- db[[Class]]
   

tags <- tools:::RdTags(temp)
# Name ----
Name <- gsub("'", "", temp[[2]][[1]][1])

# Description ----
inds <- length(temp[[5]])
store <- NULL
for (X in 2:inds) {
  store <- append(store, (temp[[5]][[X]][1]))
}
Description <- trimws(gsub("\n", "", paste(store, "", collapse="")))


# Sections 
ind <- which(tags == "\\section")


# Slots ----
tt <- temp[[ind[1]]]
st <- lapply(tt[[2]], length)[[3]]
out <- matrix(NA, nrow=st*5, ncol=2)
stnum <- 2
index <- seq(from=stnum, by=3, to=st)
ind <- 1
for (XX in seq_along(index)) {
  ind <- ind + 1 
  out[ind,1] <- tt[[2]][[3]][[index[XX]]][[1]][[1]][[1]][1]
  templength <- length(tt[[2]][[3]][[index[XX]]][[2]])
  listlength <- unlist(lapply(tt[[2]][[3]][[index[XX]]][[2]], length))
  store <- NULL
  for (X in 1:templength) {
    val <- unlist(tt[[2]][[3]][[index[XX]]][[2]][[X]][1])
    if (length(val) > 0) store <- append(store, val)
  }  
  store <-  trimws(gsub("\n", "", paste(store, "", collapse="")))
  
  out[ind,2] <- store
  
  extra <- which(listlength > 1)
  if (length(extra) > 0) {
    index2 <- seq(from=4, by=3, to=max(listlength))
    for (X in 1:max(listlength)) {
      tempval <- tt[[2]][[3]][[index[XX]]][[2]][[extra]][[X]]
      tempval <- trimws(gsub("\n", "", paste(tempval, "", collapse="")))
      if (length(tempval) >0 & tempval !="") {
        # if (nchar(tempval) > 80) {
        #   totchar <- nchar(tempval)
        #   tots <- totchar/80
        #   splocs <- gregexpr(pattern =' ', tempval)[[1]]
        #   if (sum(splocs > 70) > 1) {
        #     loc <- min(splocs[splocs > 70])
        #     locs <- seq(from=loc, by=80, to=nchar(tempval))
        #     tempval <- paste(read.fwf(textConnection(tempval),
        #                  c(locs, nchar(tempval)), as.is = TRUE), collapse = "\n")
        #   }
        # }
        ind <- ind + 1
        out[ind,2] <- tempval 
        out[ind,1] <- ""        
      }
    }
  }
  
  # if (nchar(store) > 80) {
  #   totchar <- nchar(store)
  #   tots <- totchar/80
  #   splocs <- gregexpr(pattern =' ', store)[[1]]
  #   if (sum(splocs > 70) > 1) {
  #     loc <- min(splocs[splocs > 70])
  #     locs <- seq(from=loc, by=80, to=nchar(store))
  #     store <- paste(read.fwf(textConnection(store), 
  #                  c(locs, nchar(store)), as.is = TRUE), collapse = "\n")
  #   }
  # }
  
  
}

out <- out[as.logical(apply(!apply(out, 1, is.na), 2, prod)),]



# Function call ----
Call <- NULL
if (length(ind) > 1) {
  inds <- length(temp[[ind[2]]][[2]])
  store <- NULL
  for (X in 2:inds) {
    store <- append(store, temp[[ind[2]]][[2]][[X]][1])
  }
  store <-  trimws(gsub("\n", "", paste(store, "", collapse="")))
  Call <- store
}



# Make Table ----
nrow <- 2 + length(Call) + nrow(out) + 2 
outmat <- matrix(NA, nrow=nrow, ncol=2)
outmat[1,] <- c("Name", Name)
outmat[2,] <- c("Description", Description)
ind <- 3 
if (length(Call) > 0) {
  outmat[ind,] <- c("Function call", Call)  
  ind <- 4
}
outmat[ind,] <- c("", "")
outmat[ind+1,] <- c("Slots", "")
ind <- ind+2
outmat[ind:(ind+nrow(out)-1), ] <- out




write.table(outmat, file=file.path("CheatSheets", paste0(Name, ".csv")), row.names=FALSE, 
          col.names=FALSE, sep=",")


pander(outmat)
# }
```
